version: 1.0.{build}
os: Visual Studio 2017
skip_tags: true
configuration: Debug
build_script:
- ps: dotnet restore ./Trappist/Trappist.sln
environment:  
  COVERALLS_REPO_TOKEN:
  secure: oI8JLO5/25+ZMrrWdVckNz5zqUysVlU+VVMBpPxZlEXaQ/A/6z544OcIs8rVhk49
branches:
  only:
    - development
    - staging
    - master
install:
- ps: Start-FileDownload 'https://ci.appveyor.com/api/buildjobs/xj78v6dac42uob8q/artifacts/main%2Fbin%2Fzip%2Fopencover.4.6.589.zip'
- ps: ls
- ps: 7z.exe x main%2Fbin%2Fzip%2Fopencover.4.6.589.zip ./opencover
- ps: ls
build:
  project: .\Trappist\Trappist.sln
  verbosity: minimal
test_script:
- ps: >-
   OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test ./Trappist/src/Promact.Trappist.Test" -filter:"+[Promact.Trappist.Repository*]*" -hideskipped:File -output:opencover.xml -oldStyle
     

