version: 1.0.{build}
os: Visual Studio 2017
skip_tags: true
configuration: Debug
build_script:
- ps: dotnet restore ./Trappist/Trappist.sln
branches:
  only:
    - development
build:
  project: .\Trappist\Trappist.sln
  verbosity: minimal
test_script:
- ps: >-
   cd ./trappist/src/promact.trappist.unittests
- ps: >-
   C:\Windows\system32\regsvr32.exe /s  /n /i:user "opencover.4.6.589\x86\OpenCover.Profiler.dll"
- ps: >-
   opencover.4.6.589\OpenCover.Console.exe -register:user "-target:c:\program files\dotnet\dotnet.exe" "-targetargs:test" -filter:+[Promact.Trappist*]* -oldstyle -output:opencover.xml


     

