version: 1.0.{build}
os: Visual Studio 2017
skip_tags: true
configuration: Debug
build_script:
- ps: dotnet restore ./Trappist/Trappist.sln
branches:
  only:
    - development
build:
  project: .\Trappist\Trappist.sln
  verbosity: minimal
test_script:
- ps: >-
   cd ./trappist/src/promact.trappist.unittests
- ps: >-
   opencover.4.6.589\OpenCover.Console.exe -register:Path32 "-target:c:\program files\dotnet\dotnet.exe" "-targetargs:test" -filter:+[*]* -oldstyle -output:opencover.xml
   


     

